# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # ubuntu-18.04 for file open dialog to last visit folder
        os: [ubuntu-latest]
        sku: [CAN, DEV, RUO, Non-RUO]
    env:
      TOSTADOR_SKU: ${{ github.ref_name }}-${{ matrix.sku }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $TOSTADOR_SKU
